### ISSUE TITLE
feature: Handler method for cache

### ISSUE THREAD

**Issue by pablomichelettii** [hastega/Loki#1]
Loki need a way to manage cache during development. Try to find out a way to implememnt a method for deleting it manually and a cofiguration to deleting it automatically setting up some params in the config file.

**Comment by Zenomante** [comment]
Implemented nocache call to get data from the server without caching the response
Implemented a clearCache call to clear a specific path of the cache
Pull Requested: https://github.com/hastega/Loki/pull/3
