### ISSUE TITLE
feature: Implement caching for non-GET APIs

### ISSUE THREAD

**Issue by pablomichelettii** [hastega/Loki#2]
Figure out a feature to implement caching method for non-GET Apis.

**Comment by pablomichelettii** [comment]
29/11 @pablomichelettii @GTerigiHastega  @Zenomante 
**Meeting note:** 

- [ ] use Header as instruction to do action using request.
_Maybe use the header is not the best way to implement instruction, because the headers need to be used also in the frontend and the need to be removed._ 

- [ ]  implementing pass through on post, put, patch and delete 

- [ ] better handling calling of request with new manager

- [ ] handling integration of custom middleware 
_figure out how we can implementing a managment of middleware, usage and creation_

Objective:
- [ ] better error handling 
- [x] implenting cache
- [ ] refactor unused code
- [ ] swagger docs

Future: 
Implementing electron or a simple cli gui.

**Comment by GTerigiHastega** [comment]
Basic Cache implementation done.
[Pull Request](https://github.com/hastega/Loki/pull/4)
